---
title: "R Notebook"
output: html_notebook
---

```{r}
library(data.table)
library(openxlsx)
library(tidyverse)
```

```{r}
clusters <- read.xlsx("Results/Longitudinal Clustering/8-Clusters 3-Timepoints, Random Forest Imputation, non-MUSA, Races sans Full Disagg.xlsx")

# cluster_meds <- read_csv("Results/Longitudinal Clustering/Cluster Medians.csv")

cluster_medians <- clusters %>%
  group_by(clusters, Variable, Year) %>%
  summarize(Median = round(median(Value, na.rm = T), 2),
            Range = paste0(prettyNum(round(min(Value, na.rm = T)), big.mark = ","), " - ", prettyNum(round(max(Value, na.rm = T)), big.mark = ","))) %>%
  unique() %>%
  mutate(Year = as.character(Year))

# write_csv(cluster_medians, "Results/Longitudinal Clustering/Cluster Medians.csv")
```

```{r}
regional_medians <- clusters %>%
  group_by(Variable, Year) %>%
  summarize(Regional_Median = round(median(Value, na.rm = T), 2),
            Regional_Average = round(mean(Value, na.rm = T), 2)) %>%
  unique() %>%
  mutate(Year = as.character(Year))

# write_csv(regional_medians, "Results/Longitudinal Clustering/Regional Medians.csv")

```
